In [1]:
import torch


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item

<function Tensor.item>

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
print(matrix.ndim)
matrix.shape

2


torch.Size([2, 2])

In [15]:
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
import torch

tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor Shape:", tensor_1d.shape, "| ndim:", tensor_1d.ndim)

tensor_2d = torch.tensor([[1, 2, 3]]) # Added one set of brackets
print("2D Tensor Shape:", tensor_2d.shape, "| ndim:", tensor_2d.ndim)

tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("3D Tensor Shape:", tensor_3d.shape, "| ndim:", tensor_3d.ndim)

1D Tensor Shape: torch.Size([3]) | ndim: 1
2D Tensor Shape: torch.Size([1, 3]) | ndim: 2
3D Tensor Shape: torch.Size([1, 3, 3]) | ndim: 3
